"""Masaustune kilavuz yaz."""
import os

desktop = os.path.join(os.path.expanduser('~'), 'OneDrive', 'Masaüstü')
filepath = os.path.join(desktop, 'kilavuz.txt')

lines = [
    "POLYFAST - ILK KURULUM KILAVUZU",
    "================================",
    "",
    "Bu kilavuz, Polyfast botunu ilk kez kuran kullanicinin",
    "credential sorunlariyla karsilasmadan calistirabilmesini saglar.",
    "",
    "================================================",
    "ADIM 1: GEREKLI 3 BILGI",
    "================================================",
    "",
    "Botun calismasi icin 3 bilgi gerekli:",
    "",
    "1. PRIVATE KEY (Ozel Anahtar)",
    "   - MetaMask cuzdaninizin ozel anahtari",
    "   - MetaMask > Hesap Detaylari > Ozel Anahtari Disari Aktar",
    "   - 64 karakter hex (0x dahil 66)",
    "   - KIMSEYLE PAYLASILMAZ",
    "",
    "2. POLYMARKET WALLET ADRESI (Funder)",
    "   - Bu MetaMask adresiniz DEGILDIR!",
    "   - Polymarket.com > Settings sayfasinda gorunur",
    "   - 0x ile baslayan 42 karakter",
    "",
    "3. RELAYER KEY",
    "   - Polymarket API relayer anahtari",
    "   - Claim/redeem islemleri icin gerekli",
    "   - 36 karakter UUID formati",
    "",
    "================================================",
    "ADIM 2: 3 FARKLI ADRES — KARISTIRMA!",
    "================================================",
    "",
    "Sistemde 3 farkli adres var. Bunlari karistirmak",
    "en sik karsilasilan hatadir:",
    "",
    "EOA (Signer) Adresi:",
    "  - Private key'den turetilir (otomatik)",
    "  - MetaMask'ta gorunen adres",
    "  - Order imzalamak icin kullanilir",
    "",
    "Polymarket Wallet Adresi (Funder):",
    "  - Polymarket.com > Settings > Wallet sayfasinda",
    "  - Para BURADA durur",
    "  - FUNDER olarak BU adres girilmeli",
    "",
    "!! KRITIK HATA: Funder olarak MetaMask (EOA) adresi girmek!",
    "!! SONUC: 'invalid signature' hatasi alirsiniz.",
    "!! COZUM: Polymarket wallet adresini funder olarak kullanin.",
    "",
    "================================================",
    "ADIM 3: SIGNATURE TYPE",
    "================================================",
    "",
    "signature_type = 2 (Polymarket Proxy Wallet)",
    "",
    "Bu ayar cogu kullanici icin dogrudur.",
    "Polymarket hesabiniz proxy wallet (Gnosis Safe) kullanir.",
    "",
    "Eger 'invalid signature' hatasi aliyorsaniz:",
    "  1. Funder adresi dogru mu kontrol edin",
    "     (Polymarket wallet adresi olmali, MetaMask degil!)",
    "  2. Polymarket.com'a en az bir kez giris yaptiginizdan emin olun",
    "     (proxy wallet ilk giriste deploy edilir)",
    "",
    "================================================",
    "ADIM 4: ENV DOSYASI FORMATI",
    "================================================",
    "",
    "env2.txt dosyaniza su bilgileri yazin:",
    "",
    "  private key : OZEL_ANAHTARINIZ",
    "  polymarket wallet address : POLYMARKET_CUZDANI",
    "  relayer : RELAYER_ANAHTARI",
    "",
    "ONEMLI:",
    "  - API key, API secret, API passphrase YAZMAYIN",
    "  - Bunlar private key'den otomatik turetilir",
    "  - Eski/yanlis API key kullanmak hataya yol acar",
    "",
    "================================================",
    "ADIM 5: CREDENTIAL SIFRELEME",
    "================================================",
    "",
    "Bilgileri girdikten sonra:",
    "",
    "  python scripts/encrypt_from_env2.py",
    "",
    "Bu komut:",
    "  1. Private key'den EOA adresini turetir",
    "  2. Polymarket wallet adresini funder olarak kullanir",
    "  3. API key/secret/passphrase otomatik derive eder",
    "  4. Tum bilgileri sifreleyip data/credentials.enc'e yazar",
    "",
    "================================================",
    "SIK KARSILASILAN HATALAR",
    "================================================",
    "",
    "HATA: 'invalid signature'",
    "NEDEN: Funder adresi yanlis (EOA kullanilmis)",
    "COZUM: Polymarket.com > Settings > wallet adresini kullanin",
    "",
    "HATA: 'not enough balance / allowance'",
    "NEDEN: sig_type=0 ile EOA'da USDC yok",
    "COZUM: sig_type=2 kullanin (Polymarket wallet'ta para var)",
    "",
    "HATA: '401 Unauthorized / Invalid api key'",
    "NEDEN: Eski API key kullanilmis",
    "COZUM: API key'leri silip yeniden derive edin (encrypt script)",
    "",
    "HATA: 'balance: 0'",
    "NEDEN: Yanlis signature_type veya yanlis funder",
    "COZUM: sig_type=2 + dogru Polymarket wallet adresi",
    "",
    "================================================",
    "HIZLI KONTROL LISTESI",
    "================================================",
    "",
    "[ ] Private key dogru mu (64 hex karakter)",
    "[ ] Polymarket wallet adresi dogru mu (Settings'ten)",
    "[ ] Funder = Polymarket wallet (MetaMask adresi DEGIL!)",
    "[ ] signature_type = 2",
    "[ ] Polymarket.com'a en az bir kez giris yapildi mi",
    "[ ] encrypt_from_env2.py basariyla calisti mi",
    "[ ] Balance > $0 (Polymarket wallet'ta)",
    "",
    "CREDENTIAL BILGILERINI KIMSEYLE PAYLASMAYINIZ!",
]

with open(filepath, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Kilavuz yazildi: {filepath}")
